package uk.ac.ed.inf;

public enum OrderOutcome {
    DELIVERED ,
    VALIDBUTNOTDELIVERED ,
    INVALIDCARDNUMBER ,
    INVALIDEXPIRYDATE ,
    INVALIDCVV ,
    INVALIDTOTAL ,
    INVALIDPIZZANOTDEFINED ,
    INVALIDPIZZACOUNT ,
    INVALIDPIZZACOMBINATIONMULTIPLESUPPLIERS ,
    INVALID
}
